name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run-client-tests:
    runs-on: ubuntu-latest
    name: Run Client Tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i --prefix client

      - name: Run tests
        run: npm run test --prefix client
  
  run-client-lint:
    runs-on: ubuntu-latest
    name: Run Client Lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i --prefix client

      - name: Run lint
        run: npm run lint --prefix client